name: Executar Script Diariamente

on:
  schedule:
    - cron: '0 8 * * *'   # 5h da manhã no horário de Brasília (UTC-3)
    - cron: '0 18 * * *'  # 15h da tarde no horário de Brasília (UTC-3)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar arquivo de credenciais
        env:
          CREDS_JSON: ${{ secrets.CREDS_JSON }}
        run: |
          echo "$CREDS_JSON" > creds.json

      - name: Executar o script
        run: python produtos-comissionados.py
